sonar.organization=sangeetha-murugesan-sda9
sonar.projectKey=a08d748381b979053175909bd883bfda1ca41b35
sonar.sources=client/src,server/src
sonar.tests=client/src,server/test
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info